spring:
  application:
    name: HotelBookingSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_system
    username: postgres
    password: "767089"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: simple
  mail:
    host: smtp.gmail.com
    port: 587
    username: umeshgupta050104@gmail.com
    password: rhdf pdnq utpt gynt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

resilience4j:
  ratelimiter:
    instances:
      api:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expirationMs: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8086
